### ISSUE TITLE
Urgent: Bildausschnitt wird nicht richtig aus sMapshot hochgeladen

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#10]
https://bso.swissartresearch.net/resource/?objectiri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-477654&regioniri=http%3A%2F%2Fwww.researchspace.org%2Fontology%2FImageRegion%2Fc1213b71-c332-4a97-839d-8ee18838aa2f&uri=page%3AupdateSmapshotRegionForObject

>wenn man auf sMapshot die Georeferenzierung versucht, ist der Ausschnitt viel zu klein - hochgeladen wurde er grösser:

https://smapshot.heig-vd.ch/contribute/228517

Vielen Dank
Michael

**Comment by fkraeutli** [comment]
Image has been rotated. Needed to update width and height (swap them) in order for sMapshot to accept the new region.

```sh
curl -X PUT "https://smapshot.heig-vd.ch/api/v1/images/228517/attributes" -H  "accept: application/json" -H  "Content-Type: application/json" -H "Authorization: Bearer XXX" -d "{\"height\":3306,\"width\":2563}"```
