### ISSUE TITLE
Add additional images retrieved from NB

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#11]
Folgendes Dokument zeigt in BSO keine Bilder an:
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-479968

Siehe aber helveticarchives mit Bildern:
https://www.helveticarchives.ch/detail.aspx?ID=479969

**Comment by fkraeutli** [comment]
https://bso-iiif.swissartresearch.net/iiif/2/nb-479968/info.json doesn't resolve

**Comment by fkraeutli** [comment]
@michaelmatile ich habe die Quelldaten überprüft. Das Bild wurde von der NB noch nicht auf Wikimedia hochgeladen, woher wir die Originale beziehen. Das ist bei einigen Bildern der Fall. Wenn Du das Bild benötigst, können wir evtl. bei der NB nachfragen, ob sie es hochladen oder uns schicken. Wie sollen wir verfahren?

**Comment by michaelmatile** [comment]
@fkraeutli Es handelt sich um eine Voyage pittoresque, die sehr wichtig ist - es sind folgende Einszelseiten, die dafür relevant sind:
![grafik](https://user-images.githubusercontent.com/106603320/188402567-9fd30827-d0e8-4125-8ca1-11d376159493.png)

bzw. https://www.helveticarchives.ch/archivplansuche.aspx?ID=479970

**Comment by michaelmatile** [comment]
Thank you very much!

**Comment by fkraeutli** [comment]
Ok, we have all the child records of 479970, but none of them has the images on Wikimedia, therefore it is not added to BSO. I'll write to NB to ask if they have an updated export.

**Comment by fkraeutli** [comment]
Answer from NB: remaining images will be digitised in September/October and uploaded to Wikimedia by November. They'll check if this specific set of images is part of the digitisation efforts.

**Comment by fkraeutli** [comment]
NB has sent the additional images in advance. We can add them manually

**Comment by michaelmatile** [comment]
Is there no possibility of an automatic update?

**Comment by fkraeutli** [comment]
> Is there no possibility of an automatic update?

Yes, but that would have to wait until the next release (November). Would that be ok?

**Comment by michaelmatile** [comment]
Yes, that is perfect.
