### ISSUE TITLE
Rotate SFF images that have been marked

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#28]
All images of the SFF collection has ben controled: You can effect now the actual rotation.
Thank you
Michael

**Comment by fkraeutli** [comment]
Thank you! Will proceed

**Comment by fkraeutli** [comment]
Workflow:
- change owner of images so that Cantaloupe can write them:
  - `chown 101 <id>.tif`
- rotate image
  - clockwise: `mogrify -rotate 90 <id>.tif`
  - counter-clockwise: `mogrify -rotate -90 <id>.tif`
  - upside-down: `mogrify -rotate 180 <id>.tif`
- manually adjust crop of image
