### ISSUE TITLE
Falscher Hersteller/Verleger

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#29]
Wie kann ich eine falsch zugewiesene Person löschen - hier Caspar Wolf (1525-1601)? Der Bezug stammt nicht aus helvetic archives, müsste also komplett von uns gelöscht werden können:

https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-482097
https://www.helveticarchives.ch/detail.aspx?ID=482097

Vielen Dank
Michael

**Comment by fkraeutli** [comment]
Hallo Michael,

der Bezug scheint von der NB zu stammen. Unter Descriptors steht _Verlag (Personen\W\Wolf, Caspar (1525-1601))_

<img width="1420" alt="Screenshot 2022-11-28 at 14 55 05" src="https://user-images.githubusercontent.com/1564625/204295427-880012ec-20d8-4901-a53f-98169188e78f.png">
