### ISSUE TITLE
Henzi vereinheitlichen

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#30]
[par Henzi]
Henzi, Rudolf Samuel (1731 - 1803)
Henzi, Rudolf Samuel (1731-1803)
Hentzi, R.
Hentzi Verlag
R. Hentzi

Ist dieselbe Person = GND https://d-nb.info/gnd/116723491

Falsche GND ist https://d-nb.info/gnd/1089794037
Fehler in https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Factor%2F2230D8BC-80D8-32C9-8A3C-A8EC1E36DCFA

**Comment by fkraeutli** [comment]
Merged, re-running pipeline

**Comment by fkraeutli** [comment]
Re-running pipeline due to bug in NB record preparation
