### ISSUE TITLE
Die St. Peters Insel in dem Bielersee / [Sigismund von Wagner ; gezeichnet von Franz Niklaus König und Simon Daniel Lafond] 

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#31]
Bitte schau Dir doch diesen Fall mal an - ich finde das im Workspace unter den Bilddrehungen nicht und kann dort auch die Bildtitel nicht suchen. Auch die Beteiligten lassen sich nicht suchen - ist da noch ein Fehler drin?

https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-478552

Vielen Dank
Michael

**Comment by fkraeutli** [comment]
Der Eintrag ist ein Dossier. Du müsstest nach den darin enthaltenen Bildern suchen, z.B. nb-478555
<img width="1303" alt="Screenshot 2022-12-13 at 16 34 33" src="https://user-images.githubusercontent.com/1564625/207376228-476a72d4-f3ef-49ab-a90a-89d2eb6b2c15.png">

**Comment by michaelmatile** [comment]
Das funktioniert aber eben nicht mit allen, such mal z.B. nach nb-160780. Bitte drehe alle in diesem Dossier, die hochkant stehen. Vielen Dank!

**Comment by fkraeutli** [comment]
[nb-160780](https://resource.swissartresearch.net/artwork/nb-160780) bezieht sich auf den gesamten Bestand, da sind direkt ebenfalls keine Bilder enthalten. Meinst du ein anderes?

**Comment by michaelmatile** [comment]
Es ist ein Werk, in dem 80% falsch gedreht sind - ich habe mir jetzt die Mühe genommen, jedes einzelne im Workspace anzugeben. Aber das ist jetzt nicht mehr Fehlmann-Bestand, für den ich mich verantwortlich fühle. Ich kann unmöglich für alle Daten die Korrekturen durchgeben - dafür fehlt mir schlicht die Zeit. Ich bespreche das noch mit Thomas. Das war auch nie so gedacht. Die Nachfolge von Stephanie wird hier einspringen müssen.

**Comment by fkraeutli** [comment]
ok, dann schliesse ich dieses Issue derweil
