### ISSUE TITLE
sMapshot Update funktioniert nicht

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#33]
https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-479957

**Comment by michaelmatile** [comment]
Dasselbe:
https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-479958

**Comment by michaelmatile** [comment]
Dasselbe:
https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-821089

**Comment by michaelmatile** [comment]
Das Problem, dass die Updates mit den neu gesetzten Ausschnitten nicht aktualisiert werden, scheint generell nicht zu funktionieren. Bitte überprüfe das mit sMapshot - es behindert unsere Arbeit.
Vielen Dank, herzlich
Michael
https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-479857

**Comment by fkraeutli** [comment]
Es scheint ein Problem auf Seiten von sMapshot zu sein. Bei den Observations wird der korrekte Ausschnitt angezeigt, aber im 3D Modell nicht. Ich frage mal bei sMapshot nach.

<img width="1445" alt="Screenshot 2023-02-20 at 09 30 11" src="https://user-images.githubusercontent.com/1564625/220052798-a120ff92-0d95-4fd6-b0e4-f0913dc1eb95.png">
