### ISSUE TITLE
Johann Rudolph Rahn ist kein Mitarbeiter von Aberli

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#39]
Lieber Florian
Im Netzwerk von Aberli taucht Rahn als "collaborator" auf:
https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Factor%2F6D1B151D-7CA5-3D06-8AAF-AF6E739FB0E3
bzw.:
https://bso.swissartresearch.net/resource/?uri=https%3A%2F%2Fresource.swissartresearch.net%2Factor%2F8612213B-F110-31DC-AC6B-A01357828D95

Siehst Du, wo diese falsche Verknüpfung in den Daten entsteht?

Vielen Dank
Michael

**Comment by fkraeutli** [comment]
```sparql
SELECT * WHERE {
 BIND(<https://resource.swissartresearch.net/actor/6D1B151D-7CA5-3D06-8AAF-AF6E739FB0E3>
 as ?s)
 BIND(<https://resource.swissartresearch.net/actor/8612213B-F110-31DC-AC6B-A01357828D95> as ?o)
  ?object (crm:P128_carries/crm:P94i_was_created_by|crm:P108i_was_produced_by)/crm:P14_carried_out_by ?s, ?o .
  OPTIONAL {
      ?subEvent crm:P2_has_type ?eventType ;
          crm:P14_carried_out_by ?o ;
          ^crm:P9_consists_of/(^crm:P94i_was_created_by/^crm:P128_carries|^crm:P108i_was_produced_by) ?object .
  }
  BIND(IF(BOUND(?eventType), ?eventType, search:collaborator) as ?p)
  FILTER(?s != ?o)
}
```

Ergibt ein Objekt, bei dem Aberli und Rahn aufgeführt sind:
> SARI, 2023. L'Isle de St. Jean. In Bilder der Schweiz Online. Zürich: Zentralbibliothek Zürich. Available at: https://resource.swissartresearch.net/artwork/zbz-990100688820205508. Accessed 17.04.2023

Die Daten kommen von der ZBZ: https://www.e-manuscripta.ch/zuzneb/doi/10.7891/e-manuscripta-26909

**Comment by fkraeutli** [comment]
- Updated network visualisations to not display contested statements
- Renamed unknown relation from "collaborator" to "co-occurrence"
