### ISSUE TITLE
Hinzugefügte Datierung wird nicht angezeigt

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#48]
Die neu hinzugefügte Datierung "1783-1784" wird in der Anzeige nicht dargestellt:
https://bso.swissartresearch.net/resource/artwork:SFF_D_1538?view=page

Vielen Dank!
M

**Comment by fkraeutli** [comment]
Bei “Label” muss die Datierung eingegeben werden wie sie angezeigt werden soll (momentan steht hier “Entstehung”)

![IMG_4599](https://github.com/swiss-art-research-net/bso-data-pipeline/assets/1564625/be0ea9a5-fa5b-402b-8ab6-4552a77685bb)
