### ISSUE TITLE
Fehlende Bilder

### ISSUE THREAD

**Issue by michaelmatile** [swiss-art-research-net/bso-data-pipeline#49]
Bitte überprüfen weshalb die Bilder von
https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-479968
nicht auf BSO sind.

Auf helveticarchives finde ich sie:
https://www.helveticarchives.ch/detail.aspx?ID=479968

Vielen Dank!

**Comment by fkraeutli** [comment]
In unserem Export ist kein Link zum Bild. Es scheint aber mittlerweile hochgeladen zu sein -> https://commons.wikimedia.org/wiki/File:CH-NB_-_Collection_Gugelmann_-_GS-GUGE-130-011.tif

**Comment by michaelmatile** [comment]
Was heisst das für mich? Kann ich damit rechnen, dass dieses und die dazugehörigen anderen Bilder dieser Publikation bei der nächsten Synchronisation im BSO zu finden sein werden oder gehören diese zu der Tranche, die Du erwähnt hast, die nur eventuell noch berücksichtigt werden kann?

**Comment by fkraeutli** [comment]
Im neuen Export ist es auch nicht dabei aber ich kann bei der NB nachfragen wie die Timeline ist

**Comment by michaelmatile** [comment]
Das wäre toll, vielen Dank. Diese Publikation ist für uns wichtig.

**Comment by fkraeutli** [comment]
Status: Bilder wurden von der NB übermittelt und werden derzeit in BSO integriert

**Comment by fkraeutli** [comment]
@michaelmatile Die Bilder sind nun online: https://bso.swissartresearch.net/resource/?view=page&uri=https%3A%2F%2Fresource.swissartresearch.net%2Fartwork%2Fnb-479968
